---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Guofeng Lin.
--- DateTime: 2023/11/20 06:57
---

print("hello world!!")
file = io.open("../resource/args", "r")
if file then
    print("file is exist")
else
    print("file is not exist")
end